### ISSUE TITLE
按百分比设置高度不起作用

### ISSUE THREAD

**Issue by tylerlong** [pandao/editor.md#19]
比如 `height: '60%'`,  不管设置的百分比是多少，展示出来都是最低的高度。

**Comment by tylerlong** [comment]
研究了下，这个应该不是editor.md的问题。

根据这里的提示： http://stackoverflow.com/questions/14545507/div-height-in-percentage

添加如下CSS可以让编辑器以整个页面高度为参考，按照百分比设置高度：

```css
html, body{
    height: 100%;
}
```
