### ISSUE TITLE
问题：如何更改每行前面的空格，我想每行文本前面留一些空白

### ISSUE THREAD

**Issue by wakaryry** [pandao/editor.md#97]
我想改变每行文本开始时前面的间隔：也就是不想每行都是挨着行标签输入，想增加一些空格，这样看着舒服一些。

请问一下，我应该如何去实现？

![editor1](https://cloud.githubusercontent.com/assets/7576559/7953829/0a6f4efa-09fc-11e5-8d95-12313ac55189.png)

**Comment by pandao** [comment]
@wakaryry  你可以试试这样改一下：

```css
.CodeMirror pre {
    padding: 0 15px; /* 原先只有 4px */
}
```

也算是一个间接的好提议了，下个版本想想看要不加大内间距，这样会比较美观一点。
